table Dim_Calendario
	lineageTag: ebd3f9b0-18f8-4440-b28f-ec56e2567bf1

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: a33ac73c-5e33-4436-a255-263d33d6b8ba
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 4a6efaf7-68ef-48c5-8f4b-5ca9359904a4
			defaultHierarchy: LocalDateTable_6a3f605d-8557-4d23-b18e-80407ceca597.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 7a478c72-387d-4298-bb7f-ee1a3a0b90af
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column 'Mes Número'
		dataType: int64
		formatString: 0
		lineageTag: adfbcf35-c5d9-4942-a604-d88b4ec6177c
		summarizeBy: sum
		sourceColumn: Mes Número

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: ecb7dacc-c030-4ae1-8bd4-ca0425683311
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Mes Corto'
		dataType: string
		lineageTag: 65ffee5f-c345-4b93-96c7-f6a349fc338f
		summarizeBy: none
		sourceColumn: Mes Corto

		annotation SummarizationSetBy = Automatic

	column Año-Mes
		dataType: string
		lineageTag: b84c539f-cbac-4d3f-bc22-9ceae0414dad
		summarizeBy: none
		sourceColumn: Año-Mes

		annotation SummarizationSetBy = Automatic

	column 'Mes Año'
		dataType: string
		lineageTag: bf36caae-e6be-4e18-8334-e54deb62b53d
		summarizeBy: none
		sourceColumn: Mes Año

		annotation SummarizationSetBy = Automatic

	column 'Trimestre Número'
		dataType: int64
		formatString: 0
		lineageTag: 639f2802-f786-4d78-aabc-b2604734f4dc
		summarizeBy: sum
		sourceColumn: Trimestre Número

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 8844109e-eb13-4439-9ae0-125a2f2cd580
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Año-Trimestre
		dataType: string
		lineageTag: d2f6bbfb-5c4a-4bba-a2cb-2d33b0580230
		summarizeBy: none
		sourceColumn: Año-Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Semana del Año'
		dataType: int64
		formatString: 0
		lineageTag: 3a570bb8-c1d7-4937-9348-383c222ab2a8
		summarizeBy: sum
		sourceColumn: Semana del Año

		annotation SummarizationSetBy = Automatic

	column Día
		dataType: int64
		formatString: 0
		lineageTag: 680f3e3f-7ad7-4db3-82c4-a592898d3f8e
		summarizeBy: sum
		sourceColumn: Día

		annotation SummarizationSetBy = Automatic

	column 'Día Semana Nº'
		dataType: int64
		formatString: 0
		lineageTag: 8db4c25d-85c9-4857-933f-881d16a376f7
		summarizeBy: sum
		sourceColumn: Día Semana Nº

		annotation SummarizationSetBy = Automatic

	column 'Día Semana'
		dataType: string
		lineageTag: 4e238647-3213-4ac1-9782-8e0b20e0fda3
		summarizeBy: none
		sourceColumn: Día Semana

		annotation SummarizationSetBy = Automatic

	column 'Tipo Día'
		dataType: string
		lineageTag: 3544e866-dfa3-4da5-980a-239f36d0dedf
		summarizeBy: none
		sourceColumn: Tipo Día

		annotation SummarizationSetBy = Automatic

	column 'Es Hoy'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 45a85b56-2079-4f90-9d4f-bdf30ce89363
		summarizeBy: none
		sourceColumn: Es Hoy

		annotation SummarizationSetBy = Automatic

	column 'Es Mes Actual'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2159bf14-5ea6-4aa1-bb9e-c3970f245d71
		summarizeBy: none
		sourceColumn: Es Mes Actual

		annotation SummarizationSetBy = Automatic

	column 'Es Año Actual'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9028cae0-faa4-44e8-8cd5-62c1bdb7b947
		summarizeBy: none
		sourceColumn: Es Año Actual

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source = ```
				let
				    Origen = let
				    // 1. Fuente (usa tu fact real)
				    Source = fact_energia_full_v2,
				
				    // 2. Rango dinámico
				    StartDate = Date.From(List.Min(Source[datetime])),
				    EndDate   = Date.From(List.Max(Source[datetime])),
				    TotalDays = Duration.Days(EndDate - StartDate),
				
				    // 3. Lista de fechas
				    DateList = List.Dates(StartDate, TotalDays + 1, #duration(1,0,0,0)),
				
				    // 4. Tabla base
				    Calendario = Table.FromList(DateList, Splitter.SplitByNothing(), {"Fecha"}),
				
				    // =========================
				    // COLUMNAS DE TIEMPO
				    // =========================
				
				    Año = Table.AddColumn(Calendario, "Año", each Date.Year([Fecha]), Int64.Type),
				
				    MesNumero = Table.AddColumn(Año, "Mes Número", each Date.Month([Fecha]), Int64.Type),
				
				    MesNombre = Table.AddColumn(MesNumero, "Mes", each Text.Proper(Date.ToText([Fecha], "MMMM", "es-ES")), type text),
				
				    MesCorto = Table.AddColumn(MesNombre, "Mes Corto", each Text.Proper(Date.ToText([Fecha], "MMM", "es-ES")), type text),
				
				    AñoMes = Table.AddColumn(MesCorto, "Año-Mes", each Date.ToText([Fecha], "yyyy-MM"), type text),
				
				    MesAño = Table.AddColumn(AñoMes, "Mes Año", each Text.Proper(Date.ToText([Fecha], "MMM yyyy", "es-ES")), type text),
				
				    TrimestreNum = Table.AddColumn(MesAño, "Trimestre Número", each Date.QuarterOfYear([Fecha]), Int64.Type),
				
				    Trimestre = Table.AddColumn(TrimestreNum, "Trimestre", each "T" & Text.From([Trimestre Número]), type text),
				
				    AñoTrimestre = Table.AddColumn(Trimestre, "Año-Trimestre", each Text.From([Año]) & "-T" & Text.From([Trimestre Número]), type text),
				
				    Semana = Table.AddColumn(AñoTrimestre, "Semana del Año", each Date.WeekOfYear([Fecha]), Int64.Type),
				
				    Dia = Table.AddColumn(Semana, "Día", each Date.Day([Fecha]), Int64.Type),
				
				    DiaSemanaNum = Table.AddColumn(Dia, "Día Semana Nº", each Date.DayOfWeek([Fecha], Day.Monday) + 1, Int64.Type),
				
				    DiaSemana = Table.AddColumn(DiaSemanaNum, "Día Semana", each Text.Proper(Date.ToText([Fecha], "dddd", "es-ES")), type text),
				
				    TipoDia = Table.AddColumn(DiaSemana, "Tipo Día", each if [Día Semana Nº] >= 6 then "Fin de semana" else "Laboral", type text),
				
				    // =========================
				    // COLUMNAS INTELIGENTES (FLAGS)
				    // =========================
				
				    EsHoy = Table.AddColumn(
				        TipoDia,
				        "Es Hoy",
				        each Date.From(DateTime.LocalNow()) = [Fecha],
				        type logical
				    ),
				
				    EsMesActual = Table.AddColumn(
				        EsHoy,
				        "Es Mes Actual",
				        each Date.Month([Fecha]) = Date.Month(DateTime.LocalNow()) 
				            and Date.Year([Fecha]) = Date.Year(DateTime.LocalNow()),
				        type logical
				    ),
				
				    EsAñoActual = Table.AddColumn(
				        EsMesActual,
				        "Es Año Actual",
				        each Date.Year([Fecha]) = Date.Year(DateTime.LocalNow()),
				        type logical
				    )
				
				in
				    EsAñoActual,
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Fecha", type date}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

