table fact_energia_full
	lineageTag: 857f81a6-d86c-4f57-95a4-a3f6e46c4723

	measure 'Generacion Total' =
			
			SUM(fact_energia_full[gen_solar]) +
			SUM(fact_energia_full[gen_eolica]) +
			SUM(fact_energia_full[gen_hidraulica]) +
			SUM(fact_energia_full[gen_nuclear]) +
			SUM(fact_energia_full[gen_ciclo_combinado])
		lineageTag: 9e9a5436-aeef-4770-9040-d2b21e5d1b19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: f025bbe0-cfbe-4b3c-94a3-05375adf99c8
		summarizeBy: none
		sourceColumn: datetime

		variation Variación
			isDefault
			relationship: ec647cd4-51d9-4896-8b47-b7a5bc2f6ce5
			defaultHierarchy: LocalDateTable_8a02682c-393a-4337-a748-22d870d48bfd.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column demanda_real
		dataType: double
		lineageTag: 95761fc4-e521-4783-80ba-971bb3885220
		summarizeBy: sum
		sourceColumn: demanda_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geo_id
		dataType: int64
		formatString: 0
		lineageTag: 801aa66f-f773-47d5-9c6a-5403626acc43
		summarizeBy: sum
		sourceColumn: geo_id

		annotation SummarizationSetBy = Automatic

	column geo_name
		dataType: string
		lineageTag: 163d3908-16b9-4d9c-ba72-08dfafe71788
		summarizeBy: none
		sourceColumn: geo_name

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: da51ae16-42b0-4599-ae2e-87cf7ac73a8b
		summarizeBy: none
		sourceColumn: fecha

		variation Variación
			isDefault
			relationship: ded75ea2-82e9-4341-b5a2-447637e49968
			defaultHierarchy: LocalDateTable_4f5d8383-8d86-4f09-880b-b7d26355d979.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora
		dataType: int64
		formatString: 0
		lineageTag: b7077f78-7cd9-46a9-8b7a-b64618b033a5
		summarizeBy: sum
		sourceColumn: hora

		annotation SummarizationSetBy = Automatic

	column año
		dataType: int64
		formatString: 0
		lineageTag: bb19b1a1-dc5c-4385-b57b-242c80c31480
		summarizeBy: sum
		sourceColumn: año

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: d5fc162e-2a8e-42d4-8971-4d6c6952ebc0
		summarizeBy: sum
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column indicador
		dataType: string
		lineageTag: 3d9db3c1-6665-4fb9-ac4f-f973f9f79b28
		summarizeBy: none
		sourceColumn: indicador

		annotation SummarizationSetBy = Automatic

	column demanda_prevista
		dataType: double
		lineageTag: 0209c84b-e90b-4318-b5af-1a34449a21d4
		summarizeBy: sum
		sourceColumn: demanda_prevista

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column demanda_programada
		dataType: double
		lineageTag: d637f6f9-9740-45d7-b50b-ec1a10082e25
		summarizeBy: sum
		sourceColumn: demanda_programada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column datetime_hora
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ee89988-7a28-4963-8ee3-3246d9875430
		summarizeBy: none
		sourceColumn: datetime_hora

		variation Variación
			isDefault
			relationship: 555a0cbd-23de-4e88-a648-5f01c44fe8b7
			defaultHierarchy: LocalDateTable_3e3aabd8-4dcf-4ec6-9d65-323908aff146.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column precio_mercado
		dataType: double
		lineageTag: 098d167f-f766-4a61-9a2d-7b8c3148d2c1
		summarizeBy: sum
		sourceColumn: precio_mercado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precio_ajustes
		dataType: double
		lineageTag: cc3d9f42-a286-4c6d-bb68-3ef36df9aa97
		summarizeBy: sum
		sourceColumn: precio_ajustes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_solar
		dataType: double
		lineageTag: 7dde3335-099f-4b69-b153-aea8475cc4ac
		summarizeBy: sum
		sourceColumn: gen_solar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_eolica
		dataType: double
		lineageTag: 8836aa90-23b0-4fc3-8526-66f12650bd58
		summarizeBy: sum
		sourceColumn: gen_eolica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_hidraulica
		dataType: double
		lineageTag: 48d5eccb-6fe9-4fc8-a4aa-49005987802d
		summarizeBy: sum
		sourceColumn: gen_hidraulica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_nuclear
		dataType: double
		lineageTag: fb0d26dc-98d8-493d-ace4-b1d080b86cf2
		summarizeBy: sum
		sourceColumn: gen_nuclear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_ciclo_combinado
		dataType: double
		lineageTag: 6e0d06bc-e920-4918-a669-c5a23b4212c7
		summarizeBy: sum
		sourceColumn: gen_ciclo_combinado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_energia_full = m
		mode: import
		source =
				let
				    Origen = Parquet.Document(File.Contents("C:\Users\Juan Manuel\Documents\PERSONALES\PROYECTOS\Power-BI---An-lisis-del-Mercado-El-ctrico-en-Espa-a-Datos-ESIOS\data\processed\fact_energia_full.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    Origen

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

