table Fact_Energia_ESIOS
	lineageTag: 04dac658-7d7f-4749-92ff-ba9e237860d0

	column datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 3b99add2-9fe0-4d1c-afa3-10e9c8991881
		summarizeBy: none
		sourceColumn: datetime

		variation Variación
			isDefault
			relationship: 2a726c73-3bdf-46e7-a34e-6ee081fff3f7
			defaultHierarchy: LocalDateTable_9a239cc7-7c95-4d4e-9692-6f932f832ba1.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column demanda_real
		dataType: double
		lineageTag: 398f0d4d-0ffb-42ec-9f42-201bfbec5101
		summarizeBy: sum
		sourceColumn: demanda_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geo_id
		dataType: int64
		formatString: 0
		lineageTag: d0b78fb5-1cd4-4571-bf05-00a8505cbd9b
		summarizeBy: sum
		sourceColumn: geo_id

		annotation SummarizationSetBy = Automatic

	column geo_name
		dataType: string
		lineageTag: b0c022fd-cd6f-4c32-b4d1-65ee4a1fcfa6
		summarizeBy: none
		sourceColumn: geo_name

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ca3f584-7051-479c-917d-5f255e869997
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora
		dataType: int64
		formatString: 0
		lineageTag: 361e5564-ca64-4b67-9be5-01971edd0707
		summarizeBy: none
		sourceColumn: hora

		annotation SummarizationSetBy = Automatic

	column año
		dataType: int64
		formatString: 0
		lineageTag: 1ad4aeb8-9020-4d92-8a72-74a446e85766
		summarizeBy: sum
		sourceColumn: año

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: 4306a6bd-1d51-44c7-b7c9-4cf916694123
		summarizeBy: sum
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column indicador
		dataType: string
		lineageTag: 04bb04c1-aa09-4568-a956-9b69bfbcd9b8
		summarizeBy: none
		sourceColumn: indicador

		annotation SummarizationSetBy = Automatic

	column demanda_prevista
		dataType: double
		lineageTag: 02097add-d2b9-4ac9-9373-07044825529c
		summarizeBy: sum
		sourceColumn: demanda_prevista

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column demanda_programada
		dataType: double
		lineageTag: d8894e4d-096c-4b63-a0e8-eb72fc11b63f
		summarizeBy: sum
		sourceColumn: demanda_programada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column datetime_hora
		dataType: dateTime
		formatString: General Date
		lineageTag: 47abc548-9155-4813-adf0-96856fb6459f
		summarizeBy: none
		sourceColumn: datetime_hora

		variation Variación
			isDefault
			relationship: 0bae476f-b1fb-4482-a2b6-a6326266ad04
			defaultHierarchy: LocalDateTable_a3ba82bc-9d4a-426b-a8f9-cfe963e11e36.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column precio_mercado
		dataType: double
		lineageTag: 5d257742-4af2-4043-bca2-2dce2c9a694e
		summarizeBy: sum
		sourceColumn: precio_mercado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column precio_ajustes
		dataType: double
		lineageTag: 590a343b-eea9-435e-a887-170779aafb0a
		summarizeBy: sum
		sourceColumn: precio_ajustes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_eolica
		dataType: double
		lineageTag: 43c001af-c22c-4933-879b-3a2b93de644b
		summarizeBy: sum
		sourceColumn: gen_eolica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_nuclear
		dataType: double
		lineageTag: e53765be-07b7-4442-b4f8-82a771b88786
		summarizeBy: sum
		sourceColumn: gen_nuclear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_hidraulica
		dataType: double
		lineageTag: 552c425a-1258-4977-8dca-9721c14bde42
		summarizeBy: sum
		sourceColumn: gen_hidraulica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_ciclo_combinado
		dataType: double
		lineageTag: 566e9ee8-c2b6-4d9e-9c94-eac78f16ddb3
		summarizeBy: sum
		sourceColumn: gen_ciclo_combinado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tarifa_Energia =
			
			VAR Hora = Fact_Energia_ESIOS[hora]
			VAR TipoDia = RELATED(Dim_Calendario[Tipo Día])
			RETURN
			    IF(
			        TipoDia = "Fin de semana",
			        "P3",
			        SWITCH(
			            TRUE(),
			            Hora < 8, "P3",
			            Hora >= 10 && Hora < 14, "P1",
			            Hora >= 18 && Hora < 22, "P1",
			            Hora >= 8 && Hora < 10, "P2",
			            Hora >= 14 && Hora < 18, "P2",
			            Hora >= 22 && Hora <= 23, "P2",
			            "P3"
			        )
			    )
		lineageTag: fd5db40a-b694-44dd-b982-311a7ed22437
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column gen_hulla_antracita
		dataType: double
		lineageTag: d74b3aee-b336-4f0e-8a63-f5c2f3afe933
		summarizeBy: sum
		sourceColumn: gen_hulla_antracita

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_hulla_subbituminosa
		dataType: double
		lineageTag: d427af2b-9fb0-437e-b2a9-a7e722e0cb20
		summarizeBy: sum
		sourceColumn: gen_hulla_subbituminosa

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_fuel
		dataType: double
		lineageTag: 5bbeb278-d20e-45a5-b1f2-9681f3568b59
		summarizeBy: sum
		sourceColumn: gen_fuel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_gas
		dataType: double
		lineageTag: d6bb8201-c4c6-4c66-8818-0795fffb235e
		summarizeBy: sum
		sourceColumn: gen_gas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gen Carbon' = Fact_Energia_ESIOS[gen_hulla_antracita] + Fact_Energia_ESIOS[gen_hulla_subbituminosa]
		lineageTag: 298aef36-71d7-4ac3-88c7-6f09a0a7ceee
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gen_solar
		dataType: double
		lineageTag: 07d54ad3-4dc2-4fa3-8c0b-be042113efb0
		summarizeBy: sum
		sourceColumn: gen_solar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column demanda_programada_total
		dataType: double
		lineageTag: d64d7da9-efc7-4d4f-8d41-7479a8abd27a
		summarizeBy: sum
		sourceColumn: demanda_programada_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_indisponible
		dataType: double
		lineageTag: 7bbf1f0b-acb0-47bd-a2fc-3a71877beed9
		summarizeBy: sum
		sourceColumn: pot_indisponible

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_nuclear
		dataType: double
		lineageTag: ce866952-30d3-4f24-bb0c-d61860502fd0
		summarizeBy: sum
		sourceColumn: pot_disp_nuclear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_carbon
		dataType: double
		lineageTag: b4a7d1a1-fdd9-4951-8f22-8529191f74d8
		summarizeBy: sum
		sourceColumn: pot_disp_carbon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_fuel
		dataType: double
		lineageTag: cd443329-f35f-42a5-b1ac-af9290e1f6e3
		summarizeBy: sum
		sourceColumn: pot_disp_fuel

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_gas
		dataType: double
		lineageTag: c7fb7ed4-522c-4728-b274-6356813ee82d
		summarizeBy: sum
		sourceColumn: pot_disp_gas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_eolica
		dataType: double
		lineageTag: 98c2d0b3-3011-4dc5-817c-38497cf78ed1
		summarizeBy: sum
		sourceColumn: pot_disp_eolica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_solar
		dataType: double
		lineageTag: 948214ef-6630-4e10-a7e3-99f43fa977a2
		summarizeBy: sum
		sourceColumn: pot_disp_solar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_nuclear
		dataType: double
		lineageTag: 467f11cd-ec57-4ea4-bdc2-1be2f7953c5e
		summarizeBy: sum
		sourceColumn: pot_inst_nuclear

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_carbon
		dataType: double
		lineageTag: fe7ad461-7139-4ade-a87a-3de32c0fa153
		summarizeBy: sum
		sourceColumn: pot_inst_carbon

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_ciclo_combinado
		dataType: double
		lineageTag: 66079a83-6c4e-4499-8e7d-48a9815d81d9
		summarizeBy: sum
		sourceColumn: pot_inst_ciclo_combinado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_gas
		dataType: double
		lineageTag: a8c367db-38c2-4ff3-bf60-98cd100266b3
		summarizeBy: sum
		sourceColumn: pot_inst_gas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_eolica
		dataType: double
		lineageTag: 68dfd865-25af-4638-9d42-1a8402a353a1
		summarizeBy: sum
		sourceColumn: pot_inst_eolica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_solar
		dataType: double
		lineageTag: de497f69-277b-4b00-8ed3-45395c9d110b
		summarizeBy: sum
		sourceColumn: pot_inst_solar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_disp_hidraulica
		dataType: double
		lineageTag: 59764fe8-bb31-4133-9f9e-63e6c5a82e0e
		summarizeBy: sum
		sourceColumn: pot_disp_hidraulica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pot_inst_hidraulica
		dataType: double
		lineageTag: 7447283e-afdf-4a0e-9e51-55b3b0866915
		summarizeBy: sum
		sourceColumn: pot_inst_hidraulica

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column francia_import
		dataType: double
		lineageTag: d32b3727-3b12-48b9-8598-c6b1efcb05e4
		summarizeBy: sum
		sourceColumn: francia_import

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column francia_export
		dataType: double
		lineageTag: 44d9672e-8845-4b0f-80e4-d264d4b5a569
		summarizeBy: sum
		sourceColumn: francia_export

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column portugal_import
		dataType: double
		lineageTag: 50eac74d-566a-49a8-928e-1e4c2bf40c93
		summarizeBy: sum
		sourceColumn: portugal_import

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column portugal_export
		dataType: double
		lineageTag: 335d6ced-d2bb-4351-940f-08dc2e219f8a
		summarizeBy: sum
		sourceColumn: portugal_export

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column marruecos_import
		dataType: double
		lineageTag: ac22b1c5-8ccc-4540-bf64-8d4dda23d33b
		summarizeBy: sum
		sourceColumn: marruecos_import

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column marruecos_export
		dataType: double
		lineageTag: 6abc7e09-fcb9-484e-9890-d73b13df89cc
		summarizeBy: sum
		sourceColumn: marruecos_export

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumo_mercado_libre
		dataType: double
		lineageTag: faf464a8-91bb-4ab1-8a6e-d4a134647cbb
		summarizeBy: sum
		sourceColumn: consumo_mercado_libre

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumo_mercado_regulado
		dataType: double
		lineageTag: d948fb98-88ea-402d-ac9b-e3c4b81f5937
		summarizeBy: sum
		sourceColumn: consumo_mercado_regulado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumo_directo_mercado
		dataType: double
		lineageTag: b9cea182-eb61-48e7-8539-f52773139aa1
		summarizeBy: sum
		sourceColumn: consumo_directo_mercado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column consumo_servicios_auxiliares
		dataType: double
		lineageTag: c3bc0c60-ee69-41bc-9de2-a7463122197e
		summarizeBy: sum
		sourceColumn: consumo_servicios_auxiliares

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bombeo_turbinacion
		dataType: double
		lineageTag: 04a8660f-14db-401a-8574-2e5bd6c07817
		summarizeBy: sum
		sourceColumn: bombeo_turbinacion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bombeo_consumo
		dataType: double
		lineageTag: dea5ac7d-7dfb-424f-9168-67c8fd51ebe9
		summarizeBy: sum
		sourceColumn: bombeo_consumo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column restricciones_pbf_subir
		dataType: double
		lineageTag: 7e4ac48a-4c73-44fa-9e51-7344f0fa0e87
		summarizeBy: sum
		sourceColumn: restricciones_pbf_subir

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column restricciones_pbf_bajar
		dataType: double
		lineageTag: 9fb1a426-48c6-4198-9c4a-13b606567d51
		summarizeBy: sum
		sourceColumn: restricciones_pbf_bajar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column restricciones_tr
		dataType: double
		lineageTag: 92c38749-9db4-4661-9b5e-9b63a1defc47
		summarizeBy: sum
		sourceColumn: restricciones_tr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column balance_rr
		dataType: double
		lineageTag: 70e052e1-8419-4b02-9d2d-d5f5de511dc5
		summarizeBy: sum
		sourceColumn: balance_rr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column regulacion_terciaria
		dataType: double
		lineageTag: 485674a6-c8d1-4cdb-9ad1-9feaea281dea
		summarizeBy: sum
		sourceColumn: regulacion_terciaria

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column regulacion_secundaria
		dataType: double
		lineageTag: ebbff4e0-509a-4ee7-a788-be99616da610
		summarizeBy: sum
		sourceColumn: regulacion_secundaria

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column gastos_balance
		dataType: double
		lineageTag: c52678a8-042e-421e-916d-a52509933903
		summarizeBy: sum
		sourceColumn: gastos_balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ingresos_balance
		dataType: double
		lineageTag: 5445ba5e-f00a-4e76-8ac1-1255eb38410f
		summarizeBy: sum
		sourceColumn: ingresos_balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column restricciones_tr_subir
		dataType: double
		lineageTag: 939a399e-5af2-41e6-9661-e9d58a45718e
		summarizeBy: sum
		sourceColumn: restricciones_tr_subir

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column restricciones_tr_bajar
		dataType: double
		lineageTag: 4d1f0e92-610c-4904-b6c4-aef1763c32d3
		summarizeBy: sum
		sourceColumn: restricciones_tr_bajar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column intradiario_sesion_5
		dataType: double
		lineageTag: 3b263742-b6bd-4810-8565-83eed91b2955
		summarizeBy: sum
		sourceColumn: intradiario_sesion_5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column intradiario_sesion_6
		dataType: double
		lineageTag: 74541d62-b8e8-47c4-bd61-b06a09a2fe22
		summarizeBy: sum
		sourceColumn: intradiario_sesion_6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column intradiario_sesion_7
		dataType: double
		lineageTag: 2273b65c-d8f6-45c2-ae11-58cc13bc46d8
		summarizeBy: sum
		sourceColumn: intradiario_sesion_7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desvios_subir
		dataType: double
		lineageTag: d4f532bd-b9ee-43ed-ad73-a977b65e1ff0
		summarizeBy: sum
		sourceColumn: desvios_subir

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desvios_bajar
		dataType: double
		lineageTag: 33633dab-0f56-441f-8ef6-44fc811e0f56
		summarizeBy: sum
		sourceColumn: desvios_bajar

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column energia_balance
		dataType: double
		lineageTag: 61829afa-bb35-4e75-8677-8ee26dad0f22
		summarizeBy: sum
		sourceColumn: energia_balance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column energia_no_integrable_total_pct
		dataType: double
		lineageTag: b007b509-416f-4f00-9331-2b5437fdf055
		summarizeBy: sum
		sourceColumn: energia_no_integrable_total_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column energia_no_integrable_rtt_pct
		dataType: double
		lineageTag: 5f1f035c-0861-4849-8a59-c7c106b872d9
		summarizeBy: sum
		sourceColumn: energia_no_integrable_rtt_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column energia_no_integrable_rtd_pct
		dataType: double
		lineageTag: 12f9427e-f2b3-4287-9a51-9dc8efb68ea5
		summarizeBy: sum
		sourceColumn: energia_no_integrable_rtd_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column energia_no_integrable_tiempo_real_pct
		dataType: double
		lineageTag: 8a31d83c-f7be-4975-a5d4-9027127f0277
		summarizeBy: sum
		sourceColumn: energia_no_integrable_tiempo_real_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Energia_ESIOS = m
		mode: import
		source =
				let
				    Origen = Parquet.Document(File.Contents("C:\Users\Juan Manuel\Documents\PERSONALES\PROYECTOS\Power-BI---An-lisis-del-Mercado-El-ctrico-en-Espa-a-Datos-ESIOS\data\processed\fact_energia_full_v2.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Valor reemplazado" = Table.ReplaceValue(Origen,null,0,Replacer.ReplaceValue,{"francia_import", "francia_export", "portugal_import", "portugal_export", "marruecos_import", "marruecos_export"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",null,0,Replacer.ReplaceValue,{"consumo_mercado_libre", "consumo_mercado_regulado", "consumo_directo_mercado", "consumo_servicios_auxiliares"})
				in
				    #"Valor reemplazado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

